chore(makefile): general propose

diff --git a/contrib/localnet/Makefile b/contrib/localnet/Makefile
--- a/contrib/localnet/Makefile
+++ b/contrib/localnet/Makefile
@@ -1,6 +1,18 @@
-all: submit-and-vote
+UPGRADE_NAME ?= v2.0
 
-submit-and-vote:
-	UPGRADE_NAME="v2.0" ./submit_upgrade_proposal.sh submit_and_vote
+propose-upgrade:
+	UPGRADE_NAME=$(UPGRADE_NAME) ./proposal.sh upgrade
 
-.PHONY: all submit-and-vote
+propose-general:
+	@if [ -z "$(PROPOSAL_FILE)" ]; then \
+		echo "Error: 'PROPOSAL_FILE' parameter is required for propose-general"; \
+		echo "Usage: make propose-general PROPOSAL_FILE=<proposal_file_path>"; \
+		exit 1; \
+	fi
+	@if [ ! -f "$(PROPOSAL_FILE)" ]; then \
+		echo "Error: File '$(PROPOSAL_FILE)' does not exist"; \
+		exit 1; \
+	fi
+	./proposal.sh general $(PROPOSAL_FILE)
+
+.PHONY: propose-upgrade propose-general
